### ISSUE TITLE
extended inventory

### ISSUE THREAD

**Issue by Sinon199** [JamesWilko/GoonMod#15]
I have goonmod installed and extended inventory enabled but when i go into my inventory it isn't there

**Comment by chadsten** [comment]
Does this go for Gage Coins as well? I don't see even a grayed out option to buy mods/masks with Gage Coins, but I don't believe I have collected any yet.

**Comment by JamesWilko** [comment]
You have to have the ability to purchase the mod or mask, otherwise it won't show up.
Achievement weapons mods that you get unlimited of, you can't purchase because it's redundant.
Achievement mask mods will only be able to be purchased if you own the DLC relating to them, and if you have unlocked the achievement. Infamous stuff requires you to have the correct infamy first.

**Comment by chadsten** [comment]
My issue was actually a YML configuration error, from a previous version. It all seems to be available via the standard menus now.

I may suggest having some documentation about combined YML files, and the APAPI-something.dll override when using Hoxhud/Pocohud. I realize it's not your job to do so, but it would have been quite helpful. If you're looking for help with anything, I'm happy to assist where I can.

**Comment by Joker9944** [comment]
Is this what you are looking for?
http://payday.jameswilko.com/goonmod-pocohud

It is in the FAQ by the way.
