### ISSUE TITLE
Weapon customisation doesn't work.

### ISSUE THREAD

**Issue by walale12** [JamesWilko/GoonMod#21]
I've put all the files into the mod_overrides folder, and I have enabled weapon customisation in the modifications folder. But when I try to customise a weapon, it says that the files aren't in the mod_overrides folder, and I can't apply materials/colours/patterns to any of my weapons.

**Comment by McThyzer** [comment]
When i have read the changes correctly you would have to change a file due to a typo.

Go to:
GoonModWeaponCustomizer\units\payday2\weapons\wpn_fps_ass_74_pts

and copy "wpn_fps_ass_74_b_standard.material_config" and rename the copy to "wpn_fps_ass_74_b_standard.material_confi" (without g at the end).

Or wait for the next update.

**Comment by walale12** [comment]
I've tried that, but it still says they aren't in the mod_overrides folder. I definitely just copied over the units folder and placed it in mod_overrides.

**Comment by McThyzer** [comment]
The path should be:

"mod_overrides/GoonModWeaponCustomizer/units/..."

**Comment by walale12** [comment]
I'm an idiot.
