### ISSUE TITLE
Visual customization of weapon sight applies to other weapons with same sight

### ISSUE THREAD

**Issue by YaPh1l** [JamesWilko/GoonMod#23]
Me and a friend both encountered this. I customized my CAR4 with the Speculator Sight, giving all parts the same material, pattern and color. In-game, I had the customized CAR4 and the non-customized Loco, but both with the Speculator Sight, and on the Loco, the sight had the visual customization of the CAR4's sight.

**Comment by JamesWilko** [comment]
This is a small oversight with the current implementation of loading non-customized weapons.
It'll be fixed in the next update, but if you want a temporary work-around then apply a customization to the non-customized weapon, and then use the "No Material" material to set it back to look uncustomized. Do not use the "Reset to Factory" button, or else it will delete the data and won't work.

**Comment by YaPh1l** [comment]
Thanks man, we'll wait for the update, it's no big deal. I just wanted to make sure you're aware of this :)
