### ISSUE TITLE
Menu Color Grading seems to break other various color effects in the game

### ISSUE THREAD

**Issue by Sethycakes** [JamesWilko/GoonMod#74]
When I have the Menu Color Grading mod enabled, it seems like several color effects don't work. This includes various effects like: Meth lab smoke, yellow flash from taking armor damage, flashbangs, and red screen from having no armor.

**Comment by epilimic** [comment]
I'm also getting this since the last update. Flashbangs just make my screen have duplicate blurry effects, not a white flash. The black&white overlay when you're at 3 downs isn't there at all, it's full color. Lastly, when I enable one of the shaders and then enter my inventory, it reverts to the default grading instantly.

**Comment by Afbg123** [comment]
I'm having the same problems, all color grading reverts to normal when I enter my inventory, and in-game color grading like flashbangs, going black and white after 3 downs as well yellow flashing when dodging are completely gone.

**Comment by djwetbeatz** [comment]
I've also developed this issue. Flashbangs don't work correctly, screen doesn't turn red when you lose armor, etc., and after looking into it and disabling the menu color grading mod in the options, the issue still persists, even after removing Goonmod altogether.

**Comment by JamesWilko** [comment]
Refixed this in the latest update. Colour grading now only affects the menu and won't disable any in-game screen effects.
