### ISSUE TITLE
Weapon Customization Issues

### ISSUE THREAD

**Issue by Dezhen** [JamesWilko/GoonMod#96]
After the latest patch, i have occured to a problem that i cannot customize my guns anymore. The customizations are still on the weapons, yet i cannot choose any weapon parts in the Customization Menu anymore.

**Comment by uncagedelite** [comment]
I'm having the same problem. I think it is still customizing the guns because when I click clear customizations it does something but the customization does not actually appear.

**Comment by uncagedelite** [comment]
I figured it out you need to download this file (https://steamcommunity.com/linkfilter/?url=https://github.com/JamesWilko/GoonMod/archive/WeaponCustomizerModOverrides.zip) and put it in your mod overrides folder. The new problem is it doesn't tell you that this file needs to be downloaded when you try to customize a weapon.

**Comment by JamesWilko** [comment]
@Dezhen Please double check that you've installed the weapon customizer overrides if it's the first time you're using GoonMod. If you've been using it for a while, are there any errors in your log file after opening the customizer?

@uncagedelite The override files are packaged with the GoonMod download, and the readme in the download (and on the mod page) says how to install both parts. I'll add in a warning though, since it's obviously needed.

**Comment by Dezhen** [comment]
I am using Goonmod for like over 5-6 months now. I fixed the problem by myself by using some older versions of Goonmod. All good.
